services:
  quickbite-user:
    image: quickbite-user-service:latest
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${USER_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${USER_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${USER_DB_PASSWORD}
    networks:
      - quickbite-net

  quickbite-restaurant:
    image: quickbite-restaurant-service:latest
    ports:
      - "${RESTAURANT_SERVER_PORT}:${RESTAURANT_SERVER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${RESTAURANT_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${RESTAURANT_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${RESTAURANT_DB_PASSWORD}
    networks:
      - quickbite-net

  quickbite-order:
    image: quickbite-order-service:latest
    ports:
      - "${ORDER_SERVER_PORT}:${ORDER_SERVER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${ORDER_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${ORDER_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ORDER_DB_PASSWORD}
    networks:
      - quickbite-net

  quickbite-notification:
    image: quickbite-notification-service:latest
    ports:
      - "${NOTIFICATION_SERVER_PORT}:${NOTIFICATION_SERVER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${NOTIFICATION_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${NOTIFICATION_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${NOTIFICATION_DB_PASSWORD}
    networks:
      - quickbite-net

networks:
  quickbite-net:
    external: true