version: '3.8'

services:
  core-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=banking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword

  account-service:
    build: /banking-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://core-db:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secretpassword
    depends_on:
      - core-db