version: '3.8'

services:
  core-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=banking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - banking-network

  account-service:
    build: ./banking-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://core-db:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secretpassword
    depends_on:
      - core-db
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  pg-data: