spring:
  application:
    name: banking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secretpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
